image: docker:latest

services:
  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  
before_script:
    - chmod +x ./gradlew

stages:
  - build
  - package
  - deploy

gradle-build:
  image: openjdk:17
  stage: build
  script:
    - echo "Build starting..."
    - ./gradlew assemble && java -jar build/tgservice.jar
  artifacts:
    paths:
      - build/*.jar

docker-build:
  stage: package
  script:
    - echo "Package starting..."
    - docker build --build-arg JAR_FILE=build/libs/\*.jar -t registry.gitlab.com/tgservice .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/tgservice

deploy:
  stage: deploy
  script:
    - echo "Deploy starting..."
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull tgservice"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f my-app || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -p 0.0.0.0:8001:8001 tgservice"