apiVersion: v1
kind: Namespace
metadata:
  name: tgservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgservice
  namespace: tgservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgservice
  template:
    metadata:
      namespace: tgservice
      labels:
        app: tgservice
    spec:
      containers:
        - name: tgservice
          image: cr.yandex/crpoatffns8a7vbcrg9j/tgservice
          imagePullPolicy: Always
