apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node
  template:
    metadata:
      namespace: default
      labels:
        app: test-node
    spec:
      containers:
        - name: tgservice
          image: cr.yandex/crpoatffns8a7vbcrg9j/tgservice:__VERSION__
          ports:
          - containerPort: 8001
