apiVersion: client.authentication.k8s.io/v1beta1
kind: Deployment
metadata:
  name: tgservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgservice
  template:
    metadata:
      namespace: deafult
      labels:
        app: tgservice
    spec:
      containers:
        - name: tgservice
          image: cr.yandex/crpoatffns8a7vbcrg9j/tgservice
          imagePullPolicy: Always
